# Frontend → http://peintures.local
server {
    listen 80;
    server_name peintures.local;

    location /files/ {
        proxy_pass http://minio:9000/;
        proxy_set_header Host minio;
    }

    location / {
        proxy_pass http://frontend:4200;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";   # WebSocket pour hot reload Angular
        proxy_set_header Host $host;
    }
}

# Backend API → http://api.peintures.local
server {
    listen 80;
    server_name api.peintures.local;

    client_max_body_size 20M;

    location / {
        proxy_pass http://backend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# MailHog UI → http://mail.peintures.local
server {
    listen 80;
    server_name mail.peintures.local;

    location / {
        proxy_pass http://mailhog:8025;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}
